[package]
name = "brstm-encoder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
binrw = "0.13.1"
brstm = { path = ".." }
clap = { version = "4.4.8", features = ["derive", "cargo"] }
ffmpeg-next = { git = "https://github.com/encounter/rust-ffmpeg-zmwangx.git", ref = "f6ff7f8309866e7b92ec2e1580d918274dfcd534" }
